name: Build

on:
  pull_request:
    branches: ['main']

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: pnpm/action-setup@v3
        name: Set up pnpm
        with:
          run_install: true
      - uses: actions/setup-node@v4
        name: Set up Node.js
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'
      - run: pnpm lint
        name: Lint
      - run: |
          pnpm clean
          pnpm build
        name: Build
