name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      branch:
        required: true
        description: Branch to deploy
        default: origin/main
        type: string
      environment:
        required: true
        description: 'Environment to deploy'
        default: production
        type: environment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          run_install: true
      - uses: actions/setup-node@v4
        name: Install Node.js
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - run: pnpm lint
        name: Lint
      - run: |
          pnpm clean
          pnpm build
        name: Build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'production' }}
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ./deploy.key
          sudo chmod 600 ./deploy.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        name: 'Setup SSH'
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          run_install: true
      - uses: actions/setup-node@v4
        name: Install Node.js
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - run: curl -fsS https://dotenvx.sh/ | sh
        name: Install @dotenvx/dotenvx
      - run: dotenvx run -- pnpm exec pm2 deploy ecosystem.config.cjs ${{ inputs.environment || 'production' }}
        name: Deploy to ${{ inputs.environment || 'production' }}
        env:
          APP_BRANCH: ${{ inputs.branch || 'origin/main' }}
          DOTENV_KEY: ${{ secrets.DOTENV_KEY }}
