name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      branch:
        required: true
        description: Branch to deploy
        default: origin/main
        type: string
      environment:
        required: true
        description: 'Environment to deploy'
        default: production
        type: environment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm clean
      - run: pnpm build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'production' }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ./deploy.key
          sudo chmod 600 ./deploy.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - run: curl -fsS https://dotenvx.sh/ | sh
      - run: dotenvx run -- pnpm exec pm2 deploy ecosystem.config.cjs ${{ inputs.environment || 'production' }}
        env:
          APP_BRANCH: ${{ inputs.branch || 'origin/main' }}
          DOTENV_KEY: ${{ secrets.DOTENV_KEY }}
