name: Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    environment: production
    name: Typecheck and Register
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: oven-sh/setup-bun@v2
        name: Set up bun
        with:
          bun-version: 1.3.0
      - name: Install dependencies
        run: bun ci
      - run: bun run lint
        name: Lint
        continue-on-error: true
      - run: |
          bun run clean
          bun run type-check
        name: Typecheck
      - run: |
          bun run register
        name: Register
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
  docker:
    name: Push to Docker
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - name: Set up Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            gavenda/vivy
          flavor: |
            latest=true
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - uses: docker/setup-buildx-action@v3
        name: Set up Docker Buildx
      - uses: docker/login-action@v3
        name: Login to DockerHub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        name: Build and push
        with:
          file: ./Dockerfile
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          platforms: 'linux/amd64,linux/arm64'
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
